export const TEAMS = [
  {
    id: 1,
    name: "AAGSA",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 2,
    name: "REC",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 3,
    name: "VOLUNTEER",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 4,
    name: "YSB",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 5,
    name: "WSS",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 6,
    name: "MAYAIT",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 7,
    name: "PIPE BAND",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 8,
    name: "SCOUT",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 9,
    name: "CERT",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
  {
    id: 10,
    name: "PASC",
    pointsRemaining: 110,
    playersRemaining: 11,
  },
];

export const PLAYERS = [
  {id:1,name:"Aleem Z", points: 0, allocated: 2, teamId: 1 },
  {id:2,name:"Nasir", points: 0, allocated: 0, teamId: 0 },
  {id:3,name:"Nabil K", points: 0, allocated: 0, teamId: 0 },
  {id:4,name:"Aahil", points: 0, allocated: 0, teamId: 0 },
  {id:5,name:"AliZain b", points: 0, allocated: 0, teamId: 0 },
  {id:6,name:"Ashan", points: 0, allocated: 0, teamId: 0 },
  {id:7,name:"AliShan M", points: 0, allocated: 0, teamId: 0 },
  {id:8,name:"Aman Ali", points: 0, allocated: 0, teamId: 0 },
  {id:9,name:"AliZain Aziz", points: 0, allocated: 0, teamId: 0 },
  {id:10,name:"Aly Shan", points: 0, allocated: 0, teamId: 0 },
  {id:11,name:"Ovais Ali", points: 0, allocated: 0, teamId: 0 },
  {id:12,name:"Aaraz Asif", points: 0, allocated: 0, teamId: 0 },
  {id:13,name:"Arib Abdul", points: 0, allocated: 2, teamId: 2 },
  {id:14,name:"Jaish K", points: 0, allocated: 0, teamId: 0 },
  {id:15,name:"Wahab", points: 0, allocated: 0, teamId: 0 },
  {id:16,name:"Ilf Ali Momin", points: 0, allocated: 0, teamId: 0 },
  {id:17,name:"AliZain E", points: 0, allocated: 0, teamId: 0 },
  {id:18,name:"Shamil", points: 0, allocated: 0, teamId: 0 },
  {id:19,name:"Jarif", points: 0, allocated: 0, teamId: 0 },
  {id:20,name:"Zohaib Z", points: 0, allocated: 0, teamId: 0 },
  {id:21,name:"Sanif Ali", points: 0, allocated: 0, teamId: 0 },
  {id:22,name:"Nadeem", points: 0, allocated: 0, teamId: 0 },
  {id:23,name:"Arqish", points: 0, allocated: 0, teamId: 0 },
  {id:24,name:"Mahir", points: 0, allocated: 0, teamId: 0 },
  {id:25,name:"Zainul M", points: 0, allocated: 2, teamId: 5 },
  {id:26,name:"Muzyan", points: 0, allocated: 0, teamId: 0 },
  {id:27,name:"Saqib", points: 0, allocated: 0, teamId: 0 },
  {id:28,name:"Alim M", points: 0, allocated: 0, teamId: 0 },
  {id:29,name:"Aseel", points: 0, allocated: 0, teamId: 0 },
  {id:30,name:"Izhan Iqbal", points: 0, allocated: 0, teamId: 0 },
  {id:31,name:"Ayaan Moiz", points: 0, allocated: 0, teamId: 0 },
  {id:32,name:"Riyan Syed", points: 0, allocated: 0, teamId: 0 },
  {id:33,name:"Aneeq Nizar", points: 0, allocated: 0, teamId: 0 },
  {id:34,name:"Atik", points: 0, allocated: 0, teamId: 0 },
  {id:35,name:"Shaz Rafiq", points: 0, allocated: 0, teamId: 0 },
  {id:36,name:"Aariz N", points: 0, allocated: 0, teamId: 0 },
  {id:37,name:"Kamil Momin", points: 0, allocated: 2, teamId: 6 },
  {id:38,name:"Elyan Amir", points: 0, allocated: 0, teamId: 0 },
  {id:39,name:"Zayn Momin", points: 0, allocated: 0, teamId: 0 },
  {id:40,name:"Shahzad K", points: 0, allocated: 0, teamId: 0 },
  {id:41,name:"Taufiq Dauva", points: 0, allocated: 0, teamId: 0 },
  {id:42,name:"Ali Salman", points: 0, allocated: 0, teamId: 0 },
  {id:43,name:"Sanaf Sultan", points: 0, allocated: 0, teamId: 0 },
  {id:44,name:"Rehman T", points: 0, allocated: 0, teamId: 0 },
  {id:45,name:"Shahzad T", points: 0, allocated: 0, teamId: 0 },
  {id:46,name:"Ilyaan R", points: 0, allocated: 0, teamId: 0 },
  {id:47,name:"Areej", points: 0, allocated: 0, teamId: 0 },
  {id:48,name:"Alishan Abid", points: 0, allocated: 0, teamId: 0 },
  {id:49,name:"Nazim Khoja", points: 0, allocated: 2, teamId: 7 },
  {id:50,name:"Nabeel Zahir", points: 0, allocated: 0, teamId: 0 },
  {id:51,name:"Atiullah", points: 0, allocated: 0, teamId: 0 },
  {id:52,name:"Nimish", points: 0, allocated: 0, teamId: 0 },
  {id:53,name:"Noman N", points: 0, allocated: 0, teamId: 0 },
  {id:54,name:"Naeem N", points: 0, allocated: 0, teamId: 0 },
  {id:55,name:"Zohaib Jaffer", points: 0, allocated: 0, teamId: 0 },
  {id:56,name:"Anil Akbar", points: 0, allocated: 0, teamId: 0 },
  {id:57,name:"Alzaib Rahim", points: 0, allocated: 0, teamId: 0 },
  {id:58,name:"Navroz K", points: 0, allocated: 0, teamId: 0 },
  {id:59,name:"Kashif K", points: 0, allocated: 0, teamId: 0 },
  {id:60,name:"Zohaib Kadiwal", points: 0, allocated: 0, teamId: 0 },
  {id:61,name:"Arsalan", points: 0, allocated: 2, teamId: 8 },
  {id:62,name:"Ali Hussain", points: 0, allocated: 0, teamId: 0 },
  {id:63,name:"Arsh", points: 0, allocated: 0, teamId: 0 },
  {id:64,name:"Hadi", points: 0, allocated: 0, teamId: 0 },
  {id:65,name:"Hisban", points: 0, allocated: 0, teamId: 0 },
  {id:66,name:"Nazeef", points: 0, allocated: 0, teamId: 0 },
  {id:67,name:"Nihal", points: 0, allocated: 0, teamId: 0 },
  {id:68,name:"Sahil", points: 0, allocated: 0, teamId: 0 },
  {id:69,name:"Saifil", points: 0, allocated: 0, teamId: 0 },
  {id:70,name:"Shoaib", points: 0, allocated: 0, teamId: 0 },
  {id:71,name:"Zainul", points: 0, allocated: 0, teamId: 0 },
  {id:72,name:"Zohan", points: 0, allocated: 0, teamId: 0 },
  {id:82,name:"Rafiq Nazar", points: 0, allocated: 2, teamId: 3 },
  {id:73,name:"Mehboob Ladji", points: 0, allocated: 0, teamId: 0 },
  {id:74,name:"Imtiaz Wali", points: 0, allocated: 0, teamId: 0 },
  {id:75,name:"Dilawar Virani", points: 0, allocated: 0, teamId: 0 },
  {id:76,name:"Barkat Noor Md", points: 0, allocated: 0, teamId: 0 },
  {id:77,name:"Salim Sadruddin", points: 0, allocated: 0, teamId: 0 },
  {id:78,name:"Rafiq Ladji", points: 0, allocated: 0, teamId: 0 },
  {id:79,name:"Hazrat Hussain ", points: 0, allocated: 0, teamId: 0 },
  {id:80,name:"Shamsuddin", points: 0, allocated: 0, teamId: 0 },
  {id:81,name:"Imran Abdul", points: 0, allocated: 0, teamId: 0 },
  {id:83,name:"Rafiq Nazar", points: 0, allocated: 0, teamId: 0 },
  {id:84,name:"Shoaib S", points: 0, allocated: 0, teamId: 0 },
  {id:85,name:"Shahul", points: 0, allocated: 2, teamId: 4 },
  {id:86,name:"Shehzad", points: 0, allocated: 0, teamId: 0 },
  {id:87,name:"Shehzad Ali", points: 0, allocated: 0, teamId: 0 },
  {id:88,name:"Nabeel", points: 0, allocated: 0, teamId: 0 },
  {id:89,name:"Irfan", points: 0, allocated: 0, teamId: 0 },
  {id:90,name:"Moiz", points: 0, allocated: 0, teamId: 0 },
  {id:91,name:"Imran", points: 0, allocated: 0, teamId: 0 },
  {id:92,name:"Naish", points: 0, allocated: 0, teamId: 0 },
  {id:93,name:"Nousif", points: 0, allocated: 0, teamId: 0 },
  {id:94,name:"Noman", points: 0, allocated: 0, teamId: 0 },
  {id:95,name:"Khaydin", points: 0, allocated: 0, teamId: 0 },
  {id:96,name:"Afzal", points: 0, allocated: 0, teamId: 0 },
];
